apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemstore-orders-bff
  namespace: nemstore-dev
  labels:
    app.kubernetes.io/name: nemstore-orders-bff
    app.kubernetes.io/instance: "build-number"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: nemstore
    app.kubernetes.io/managed-by: kubectl
spec: 
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nemstore-orders-bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nemstore-orders-bff
    spec:
      containers:
        - name: nemstore-orders-bff
          image: nemstore-orders-bff:1.0.0
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: "productsCatalogApiUrl"
            value: "nemstore-productscatalog.nemstore-dev.svc.cluster.local:80"
          - name: "ordersApiUrl"
            value: "nemstore-orders.nemstore-dev.svc.cluster.local:80"
          ports:
          - containerPort: 80

              
---
apiVersion: v1
kind: Service
metadata:
  name: nemstore-orders-bff
  namespace: nemstore-dev
  labels:
    app.kubernetes.io/name: nemstore-orders-bff
    app.kubernetes.io/instance: "build-number"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: nemstore
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nemstore-orders-bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80