apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  namespace: k8s-playground
  labels:
    app: serviceb
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
        - name: serviceb
          image: k8s-playground_serviceb:k8s
          ports:
          - containerPort: 80
              
---
apiVersion: v1
kind: Service
metadata:
  name: serviceb
  namespace: k8s-playground
spec:
  type: ClusterIP
  selector:
    app: serviceb
  ports:
    - protocol: TCP
      port: 6002
      targetPort: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serviceb
  namespace: k8s-playground
spec:
  hosts:
    - serviceb.k8s-playground.svc.cluster.local
  http:
  - match:
    - port: 6002
    route:
    - destination:
        host: serviceb.k8s-playground.svc.cluster.local
        port:
          number: 6002